### ISSUE TITLE
Implement ship placement action

### ISSUE THREAD

**Issue by KSARK** [cs361w2019-osu/sprint1-project-group-14#3]
**Story**: Placing Ships

As a strategic player, I would like to be able to place my ships anywhere I want so that I can customize my game play.

**Estimated**: 2 hours

---

To complete the placement action, we need to modify the board and square classes.

A unit test for the board class is also required to test for out-of-bounds placement, collisions, and uniqueness.

A unit test for the square class is also required to test for equality.

The implement of placement will be in branch `feat-placement`

**Comment by Aqcurate** [comment]
Since attacking has not yet been implemented, comment out attack sections to test.

In game.js, comment out:
```
    // markHits(game.opponentsBoard, "opponent", "You won the game");
    // markHits(game.playersBoard, "player", "You lost the game");
```

In Game.java, comment out:
```
/*
        boolean opponentPlacedSuccessfully;
        do {
            // AI places random ships, so it might try and place overlapping ships
            // let it try until it gets it right
            opponentPlacedSuccessfully = opponentsBoard.placeShip(new Ship(ship.getShipName()), randRow(), randCol(), randVertical());
        } while (!opponentPlacedSuccessfully);
*/
```

**Comment by Aqcurate** [comment]
See feature #5.
